In [1]:
import official_xdeepfm
import torch

In [2]:
%load_ext autoreload
%autoreload 2

In [5]:
# 2: number of features (m)
# 5: number of features for each layer (H_k)
net = official_xdeepfm.CompressedInteractionNetwork(2, [5, 5], False)
print(net)

CompressedInteractionNetwork(
  (conv_layers): ModuleList(
    (0): Conv1d(4, 5, kernel_size=(1,), stride=(1,))
    (1): Conv1d(10, 5, kernel_size=(1,), stride=(1,))
  )
  (fc): Linear(in_features=10, out_features=1, bias=True)
)


In [8]:
X = torch.tensor([
    [
        [1, 1, 1],
        [2, 2, 2]
    ]
]).float()

net(X)

tensor([[0.4489]], grad_fn=<AddmmBackward0>)

In [9]:
import numpy as np

In [22]:
np.cumsum([3, 5])

array([3, 8])

In [12]:
np.array((0, *np.cumsum([3, 5])[:-1]))

array([0, 3])

In [17]:
import torch

In [20]:
torch.zeros((2, 3, 4)).flatten(1, 2)

tensor([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])